
[general]
	#The material blacklist of this module.
	materialBlacklist = ["arcane_gold", "azure_silver", "calorite", "crimson_iron", "desh", "iesnium", "ostrum"]

[recipes]
	#The materials that should not have pressing to plate recipes added.
	toPlateMaterialBlacklist = []

