#.
#Migrate copycats to Create: Copycats+ when they receive a block update
migrateCopycatsOnBlockUpdate = false
#.
#Migrate copycats to Create: Copycats+ when their block entities are initialized
migrateCopycatsOnInitialize = false

#.
#Enable/disable features. Values on server override clients
[features]
	#.
	fluid_vessel = true
	bamboo_window = true
	item_silo = true
	inverted_clutch = true
	empty_fan_catalyst = true
	parallel_gearbox = true
	cherry_window = true
	centrifugal_clutch = true
	copycat_slab = false
	overstress_clutch = true
	brake = true
	copycat_block = false
	copycat_fence_gate = false
	copycat_stairs = false
	large_crank_wheel = true
	brass_gearbox = true
	copycat_vertical_step = false
	copycat_wall = false
	six_way_gearbox = true
	crank_wheel = true
	fan_freezing_catalyst = false
	encased_chain_cogwheel = true
	sequenced_pulse_generator = true
	freewheel_clutch = true
	shear_pin = true
	inverted_gearshift = true
	linked_transmitter = true
	copycat_beam = false
	copycat_board = false
	copycat_fence = false

