#This should under no circumstances be set to true in modpacks
#If set to true, the mod creates a new global folder, that is global for your user on your computer.
#The created folders will be:
# <user_home>/.minecraft_global_packs/required_datapacks
# <user_home>/.minecraft_global_packs/optional_datapacks
# <user_home>/.minecraft_global_packs/required_resourcepacks
# <user_home>/.minecraft_global_packs/optional_resourcepacks
enable_system_global_packs = false

#This config allows you to add or remove folders or single files as Data-/Resourcepacks
#For that simply specify the file path to the folder/file relative to your .minecraft or instance folder
#With the current config you can place a Datapack into '.minecraft/global_packs/required_data' to force enable a datapack.
[resourcepacks]
required = [
]

[datapacks]
required = [
	"resourcepacks/Alex's Titles.zip",
	"resourcepacks/BetterEndCities-Vanilla.zip",
	"resourcepacks/Create Immersive Aircrafts Datapack 1.20.1 - 1.2.zip",
	"resourcepacks/default_skill_tree-0.1.0-1.20.zip",
	"resourcepacks/double shulker shells v1.3.7 (MC 1.20-1.20.6).zip",
	"resourcepacks/idasalexsmobs-1.20.zip",
	"resourcepacks/intstrong_alexsmobs-1.0.0-1.20.1.zip",
	"resourcepacks/larger phantoms v1.2.8 (MC 1.20-1.20.6).zip",
	"resourcepacks/name colors v1.0.5 (MC 1.20-1.20.6).zip",
	"resourcepacks/NoMoreFloatingIslands-1.20.4.zip",
	"resourcepacks/silence mobs v1.2.2 (MC 1.20-1.20.6).zip",
	"resourcepacks/SkyVillages-WaystonesCompat-1.20.1-1.0.3-fabric.zip",
	"resourcepacks/VanillaTweaks_c590968_MC1.20-1.20.6.zip",
	"resourcepacks/villager death messages v1.2.9 (MC 1.20-1.20.6).zip",
	"resourcepacks/villager workstation highlights v1.1.7 (MC 1.20-1.20.6).zip",
	"resourcepacks/explorations_scarecrow_tweaker.zip",
	"resourcepacks/anti enderman grief v1.1.8 (MC 1.21-1.21.1).zip",
	"resourcepacks/confetti creepers v2.2.8 (MC 1.20-1.20.6)",
	"resourcepacks/terralith_no_poop.zip"
]

optional = [
]